
CREATE TABLE Hero (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL,
    Class VARCHAR(100),
    Level INT DEFAULT 1
);

CREATE TABLE Apprentice (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL,
    MentorId INT NOT NULL
);

CREATE TABLE Skill (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL,
    Description VARCHAR(100)
);